import { Test, TestingModule } from "@nestjs/testing";
import { MemStorageService } from "./mem-storage.service";
import { InsertUser, Progress, QuizAttempt } from "shared/schema";
import { Json } from "drizzle-zod/utils";

describe("MemStorageService", () => {
  let service: MemStorageService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [MemStorageService],
    }).compile();

    service = module.get<MemStorageService>(MemStorageService);
    // Call onModuleInit to simulate module initialization
    await service.onModuleInit();
  });

  describe("Module initialization", () => {
    it("should create a default demo user on initialization", async () => {
      const demoUser = await service.getUserByUsername("demo");
      expect(demoUser).toBeDefined();
      expect(demoUser?.username).toBe("demo");
      expect(demoUser?.password).toBe("demo");
    });
  });

  describe("User methods", () => {
    it("should create a user successfully", async () => {
      const mockUserData: InsertUser = {
        username: "testuser",
        password: "testpass",
      };

      const user = await service.createUser(mockUserData);

      expect(user).toEqual({
        id: expect.any(Number),
        ...mockUserData,
      });
    });

    it("should get user by id", async () => {
      const mockUserData: InsertUser = {
        username: "testuser",
        password: "testpass",
      };

      const createdUser = await service.createUser(mockUserData);
      const user = await service.getUser(createdUser.id);

      expect(user).toEqual(createdUser);
    });

    it("should get user by username", async () => {
      const mockUserData: InsertUser = {
        username: "testuser",
        password: "testpass",
      };

      const createdUser = await service.createUser(mockUserData);
      const user = await service.getUserByUsername(mockUserData.username);

      expect(user).toEqual(createdUser);
    });

    it("should return undefined for non-existent user", async () => {
      const user = await service.getUser(999);
      expect(user).toBeUndefined();
    });``

    it("should return undefined for non-existent username", async () => {
      const user = await service.getUserByUsername("nonexistent");
      expect(user).toBeUndefined();
    });
  });

  describe("Progress methods", () => {
    it("should get user progress", async () => {
      const userId = 1;
      const progress = await service.getUserProgress(userId);

      expect(progress).toEqual([]);
    });

    it("should update user progress", async () => {
      // Omitting id as it's expected to be generated by the service
      const mockProgressData = {
        userId: 1,
        tutorialId: "tutorial-1",
        completed: true,
        quizCompleted: true,
        lastViewed: new Date().toISOString(),
      };

      const progress = await service.updateUserProgress(mockProgressData);

      expect(progress).toEqual({
        ...mockProgressData,
        id: expect.any(Number)
      });
    });

    it("should update existing progress", async () => {
      const mockProgressData = {
        userId: 1,
        tutorialId: "tutorial-1",
        completed: true,
        quizCompleted: true,
        lastViewed: new Date().toISOString(),
      };

      const firstProgress = await service.updateUserProgress(mockProgressData);
      const updatedProgress = await service.updateUserProgress({
        ...mockProgressData,
        completed: false,
      });

      expect(updatedProgress).toEqual({
        ...firstProgress,
        completed: false,
      });
    });

    it("should handle progress with optional fields", async () => {
      const mockProgressData = {
        userId: 1,
        tutorialId: "tutorial-1",
      };

      const progress = await service.updateUserProgress(mockProgressData);

      expect(progress).toEqual({
        ...mockProgressData,
        id: expect.any(Number),
        completed: false,
        quizCompleted: false,
        lastViewed: null,
      });
    });
  });

  describe("Quiz attempt methods", () => {
    it("should save quiz attempt", async () => {
      // Omitting id as it's expected to be generated by the service
      const mockAttemptData = {
        userId: 1,
        tutorialId: "tutorial-1",
        score: 80,
        answers: {} as Json,
        attemptedAt: new Date().toISOString(),
      };

      const attempt = await service.saveQuizAttempt(mockAttemptData);

      expect(attempt).toEqual({
        ...mockAttemptData,
        id: expect.any(Number)
      });
    });

    it("should get quiz attempts", async () => {
      const mockAttemptData = {
        userId: 1,
        tutorialId: "tutorial-1",
        score: 80,
        answers: {} as Json,
        attemptedAt: new Date().toISOString(),
      };

      const savedAttempt = await service.saveQuizAttempt(mockAttemptData);
      const attempts = await service.getQuizAttempts(1, "tutorial-1");

      expect(attempts).toEqual([savedAttempt]);
    });

    it("should update progress when saving quiz attempt", async () => {
      const mockAttemptData = {
        userId: 1,
        tutorialId: "tutorial-1",
        score: 80,
        answers: {} as Json,
        attemptedAt: new Date().toISOString(),
      };

      await service.saveQuizAttempt(mockAttemptData);
      const progress = await service.getUserProgress(1);

      expect(progress[0]).toEqual({
        id: expect.any(Number),
        userId: 1,
        tutorialId: "tutorial-1",
        completed: true,
        quizCompleted: true,
        lastViewed: mockAttemptData.attemptedAt,
      });
    });

    it("should return empty array for non-existent quiz attempts", async () => {
      const attempts = await service.getQuizAttempts(999, "nonexistent");
      expect(attempts).toEqual([]);
    });
  });
});
